# Generated by Django 5.0.4 on 2024-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.TextField(max_length=1000)),
                ('hprice', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('entered_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
            ],
        ),
    ]
